version: 0.0
os: linux
files:
  - source: HotelSistem/Hotel.Domain/api
    destination: /var/www/api
  - source: scripts/
    destination: /var/www/hotelsistem/scripts
  - source: buildspec.yml
    destination: /var/www/hotelsistem/buildspec.yml
  - source: HotelSistem.service
    destination: /var/www/hotelsistem/HotelSistem.service
hooks:
  BeforeInstall:
    - location: /var/www/hotelsistem/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /var/www/hotelsistem/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /var/www/hotelsistem/scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: /var/www/hotelsistem/scripts/validate_service.sh
      timeout: 300
      runas: root
