version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get update
      - sudo apt-get install -y dotnet-sdk-8.0
      - dotnet --version
  pre_build:
    commands:
      - echo Restoring dependencies
      - dotnet restore
  build:
    commands:
      - echo Building the solution in Debug and Release configurations
      - dotnet build HotelSistem.sln --configuration Debug
      - dotnet build HotelSistem.sln --configuration Release
  post_build:
    commands:
      - echo Running unit tests
      - dotnet test
    
artifacts:
  files:
    - '**/*'
    - 'appspec.yml'
