version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Build completed on `date`
      - dotnet test --configuration Release

artifacts:
  files:
    - '**/*'
