version: '3.8'

services:
  web:
    image: eduardokroetz/aspnet-hotelsystem-api:1.0
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
