version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing .NET Core
      - dotnet --version
  pre_build:
    commands:
      - echo Restoring dependencies
      - dotnet restore
  build:
    commands:
      - echo Building the solution in Debug and Release configurations
      - dotnet build HotelSistem.sln --configuration Debug
      - dotnet build HotelSistem.sln --configuration Release
  post_build:
    commands:
      - echo Running unit tests
      - dotnet test

artifacts:
  files:
    - '**/*'
