name: HotelSistemAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest 

    env:
      Solution_Name: HotelSistem                    
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      LANG: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up locale
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen pt_BR.UTF-8
        sudo update-locale LANG=pt_BR.UTF-8

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build HotelSistem.sln -c ${{ matrix.configuration }}

    - name: Execute unit tests
      run: dotnet test --no-build --configuration ${{ matrix.configuration }}

    - name: Check file encoding
      run: |
        find . -type f -name '*.cs' -exec file -i {} \;
