name: HotelSistemAPI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest 

    env:
      Solution_Name: HotelSistem                    

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore dependencies
      run: dotnet restore 

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test


    - name: Install NuGet packages for Hotel.Domain
      run: |
        cd Hotel.Domain
        dotnet add package Microsoft.AspNetCore.OpenApi --version 8.0
        dotnet add package Microsoft.EntityFrameworkCore --version 8.0
        dotnet add package Microsoft.EntityFrameworkCore.Design --version 8.0
        dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 8.0

    - name: Install NuGet packages for Hotel.Tests
      run: |
        cd Hotel.Tests
        dotnet add package Microsoft.EntityFrameworkCore.InMemory --version 8.0
        dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 8.0

 
    - name: Build the application
      run: dotnet build HotelSistem.sln --configuration ${{ matrix.configuration }}
